---
title: "Themed dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sidrar)
library(tidyverse)
library(deflateBR)
library(plotly)
library(lubridate)
library(shiny)


# Install thematic and un-comment for themed static plots (i.e., ggplot2)
 #thematic::thematic_rmd()
 thematic::thematic_shiny()

 
 gera_trimestres<- function(ano){
  
  ano<-ano
  purrr::map_chr(1:3, function(trimestre){
    stringr::str_c(ano,"0", trimestre)
  })
}


gera_meses_trimestre<- function(trimestre_codigo){
  as.Date(paste0(
    str_sub(trimestre_codigo,1,4),
    "-",
    (as.numeric(str_sub(trimestre_codigo,5,6)))*3,
    "-01"))
}


gera_meses_trimestre("201603")

calculate_next_month <- function(input_date) {
  input_date <- as.Date(input_date)  # Convert input to Date object
  next_month <- input_date %m+% months(1)  # Add 1 month to the input date
  return(next_month)
}


lista_trimestres<- unlist(lapply(1996:2023, gera_trimestres)) 

cnt_vt_precos_correntes<- 
  get_sidra(x = 1846,
            period = lista_trimestres)

cnt_vt_precos_correntes <- janitor::clean_names(cnt_vt_precos_correntes)



```

Column 
-----------------------------------------------------------------------

### Evolução - Valores correntes

```{r}

renderPlotly({
  
  sel_data<-
    cnt_vt_precos_correntes %>%
    filter(setores_e_subsetores_codigo %in% c("90687", "90691", "90696")) %>%
    mutate(data_nominal = gera_meses_trimestre(trimestre_codigo)) %>%
    filter(data_nominal == "2020-06-01")
  
  
  
  graf<-
    cnt_vt_precos_correntes %>%
    filter(setores_e_subsetores_codigo %in% c("90687", "90691", "90696")) %>%
    mutate(data_nominal = gera_meses_trimestre(trimestre_codigo)) %>%
    ggplot(aes(x = data_nominal, y = valor/10^3, group = setores_e_subsetores, color = setores_e_subsetores)) +
    geom_line() +
    geom_point(data = sel_data) +
    geom_text(data= sel_data, aes(label= str_wrap(paste0(format(data_nominal,"%d/%m/%Y"),": ", round(valor/10^3,1)),10)),color="white") +
    theme(
      axis.title.x = element_blank(),
      panel.background = element_rect(fill="#1d1d1d"),
      panel.grid = element_line(color=  "#101010"),
      text= element_text(color = "#101010" )
        
    )+
    labs(
      y= "Valores em R$ bi"
    )
  
  #graf
  
  plotly::ggplotly()
  
  
})



```


Column 
-----------------------------------------------------------------------


### Evolução - Valores constantes para último trimestre

```{r}

renderPlotly({
  
  sel_data<-
 cnt_vt_precos_correntes %>%
  filter(setores_e_subsetores_codigo %in% c("90687", "90691", "90696")) %>%
  mutate(data_nominal = gera_meses_trimestre(trimestre_codigo)) %>%
  filter(data_nominal == "2020-06-01") %>%
  mutate(data_calculo = calculate_next_month(data_nominal)) %>%
  mutate(valor_constante = deflate(valor,  data_calculo,"09/2023", index= "ipca") ) 


graf<-
cnt_vt_precos_correntes %>%
  filter(setores_e_subsetores_codigo %in% c("90687", "90691", "90696")) %>%
  mutate(data_nominal = gera_meses_trimestre(trimestre_codigo)) %>%
  mutate(data_calculo = calculate_next_month(data_nominal)) %>%
  mutate(valor_constante = deflate(valor,  data_calculo,"09/2023", index= "ipca") )  %>%
  ggplot(aes(x = data_nominal, y = valor_constante/10^3, group = setores_e_subsetores, color = setores_e_subsetores)) +
  geom_line()+
  geom_point(data = sel_data) +
  geom_text(data= sel_data, aes(label= str_wrap(paste0(format(data_nominal,"%d/%m/%Y"),": ", round(valor_constante/10^3,1)),10)),color="white") +
  theme(
    axis.title.x = element_blank()
  )+
  labs(
    y= "Valores em R$ bi"
  )
  


plotly::ggplotly()

  
})



```
